-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 19:53:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema book_ratings
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book_ratings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_ratings` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema refri_man
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema refri_man
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `refri_man` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `book_ratings` ;

-- -----------------------------------------------------
-- Table `book_ratings`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_ratings`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `author` VARCHAR(100) NULL DEFAULT NULL,
  `genre` VARCHAR(100) NULL DEFAULT NULL,
  `release_year` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `refri_man` ;

-- -----------------------------------------------------
-- Table `refri_man`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refri_man`.`category` (
  `cat_name` VARCHAR(255) NOT NULL,
  `exp_day` INT NOT NULL,
  PRIMARY KEY (`cat_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `refri_man`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refri_man`.`user` (
  `user_id` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `user_psw` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `refri_man`.`refri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refri_man`.`refri` (
  `refri_id` VARCHAR(255) NOT NULL,
  `refri_name` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`refri_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `refri_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `refri_man`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `refri_man`.`contain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refri_man`.`contain` (
  `refri_id` VARCHAR(255) NOT NULL,
  `food_name` VARCHAR(255) NOT NULL,
  `input_date` DATE NOT NULL,
  `exp_date` DATE NULL DEFAULT NULL,
  `cat_name` VARCHAR(255) NOT NULL,
  `count` INT NOT NULL,
  `type` ENUM('냉장', '냉동') NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`food_name`, `input_date`, `refri_id`),
  UNIQUE INDEX `food_name` (`food_name` ASC, `input_date` ASC) VISIBLE,
  INDEX `cat_name` (`cat_name` ASC) VISIBLE,
  INDEX `idx_food_refri_date` (`food_name` ASC, `refri_id` ASC, `input_date` ASC) VISIBLE,
  INDEX `idx_food_input_date` (`food_name` ASC, `input_date` ASC) VISIBLE,
  INDEX `contain_ibfk_1` (`refri_id` ASC) VISIBLE,
  CONSTRAINT `contain_ibfk_1`
    FOREIGN KEY (`refri_id`)
    REFERENCES `refri_man`.`refri` (`refri_id`)
    ON DELETE CASCADE,
  CONSTRAINT `contain_ibfk_2`
    FOREIGN KEY (`cat_name`)
    REFERENCES `refri_man`.`category` (`cat_name`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `refri_man`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refri_man`.`history` (
  `history_id` INT NOT NULL AUTO_INCREMENT,
  `food_name` VARCHAR(255) NOT NULL,
  `input_date` DATE NOT NULL,
  `refri_id` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`history_id`),
  INDEX `refri_id` (`refri_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `history_ibfk_1`
    FOREIGN KEY (`refri_id`)
    REFERENCES `refri_man`.`refri` (`refri_id`)
    ON DELETE CASCADE,
  CONSTRAINT `history_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `refri_man`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `refri_man`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refri_man`.`notification` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(255) NOT NULL,
  `food_name` VARCHAR(255) NOT NULL,
  `input_date` DATE NOT NULL,
  `notify_date` DATE NOT NULL,
  PRIMARY KEY (`notification_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `food_name` (`food_name` ASC, `input_date` ASC) VISIBLE,
  CONSTRAINT `notification_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `refri_man`.`user` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `notification_ibfk_2`
    FOREIGN KEY (`food_name` , `input_date`)
    REFERENCES `refri_man`.`contain` (`food_name` , `input_date`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `refri_man` ;

-- -----------------------------------------------------
-- procedure decrease_count
-- -----------------------------------------------------

DELIMITER $$
USE `refri_man`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `decrease_count`(
    IN p_refri_id VARCHAR(255),
    IN p_food_name VARCHAR(255),
    IN p_input_date DATE,
    IN p_decrement INT
)
BEGIN
    DECLARE current_count INT;

    -- 현재 count 값 확인
    SELECT count INTO current_count
    FROM contain
    WHERE refri_id = p_refri_id
      AND food_name = p_food_name
      AND input_date = p_input_date;

    -- count가 0 이하로 감소하면 삭제
    IF current_count - p_decrement <= 0 THEN
        DELETE FROM contain
        WHERE refri_id = p_refri_id
          AND food_name = p_food_name
          AND input_date = p_input_date;
    ELSE
        -- count 감소
        UPDATE contain
        SET count = count - p_decrement
        WHERE refri_id = p_refri_id
          AND food_name = p_food_name
          AND input_date = p_input_date;
    END IF;
END$$

DELIMITER ;
USE `refri_man`;

DELIMITER $$
USE `refri_man`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `refri_man`.`after_insert_contain_to_history`
AFTER INSERT ON `refri_man`.`contain`
FOR EACH ROW
BEGIN
    INSERT INTO history (food_name, input_date, refri_id, user_id)
    SELECT NEW.food_name, NEW.input_date, NEW.refri_id, r.user_id
    FROM refri r
    WHERE r.refri_id = NEW.refri_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into category values('과일', 2);
insert into category values('생선', 2);
insert into category values('소스', 7);
insert into category values('유제품', 3);
insert into category values('육류', 2);
insert into category values('음료', 14);
insert into category values('채소', 4);
